apiVersion: platform.my-org.co/v1alpha1
kind: ApiClaim
metadata:
  name: example-api-claim
spec:
  ingressRef: my-ingress # Reference to an existing XIngress resource
  apiName: "Example"
  apiPath: "example"
  apiProtocols: 
    - "https"
  swaggerDefinition: https://raw.githubusercontent.com/swagger-api/swagger-petstore/refs/heads/master/src/main/resources/openapi.yaml