apiVersion: azure.platform.my-org.co/v1alpha1
kind: XIngress
metadata:
  name: my-ingress-composite
spec:
  name: my-ingress
  location: UK
  apiManagement:
    publisherEmail: devops@my-org.co
    publisherName: DevOps Team
    skuName: Developer_1
  networking:
    vnetAddressSpace:
      - 10.0.0.0/16
    subnetPrefix:
      - 10.0.1.0/24
  # Resource names are optional - by default they will be derived from the xingress name
  # resourceNames:
  #   resourceGroup: rg-custom-name
  #   vnet: vnet-custom-name
  #   subnet: subnet-custom-name