apiVersion: platform.my-org.co/v1alpha1
kind: ApiClaim
metadata:
  name: example-api-claim
spec:
  ingressRef: my-ingress # Reference to an existing XIngress resource
  apiName: "Example"
  apiPath: "example"
  apiProtocols: 
    - "https"
  swaggerFormat: "openapi" # Optional, defaults to openapi
  swaggerDefinition: |
    openapi: 3.0.0
    info:
      title: Example API
      version: 1.0.0
    paths:
      /example:
        get:
          summary: Example endpoint
          responses:
            '200':
              description: Successful response
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "This is an example response"
  backendUrl: "https://example-api-function.azurewebsites.net/api"