apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xingress-composite
spec:
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      patchSets:
        - name: common-labels
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: spec.name
              toFieldPath: metadata.labels.xingress
      resources:
        - name: api-gateway
          base:
            apiVersion: apimanagement.azure.upbound.io/v1beta1
            kind: Gateway
            spec:
              forProvider:
                apiManagementIdSelector:
                  matchControllerRef: true
                description: Example API Management gateway
                locationData:
                - city: example city
                  district: example district
                  name: example name
                  region: example region
          patches:
            - type: PatchSet
              patchSetName: common-labels
        - name: api-management
          base:
            apiVersion: apimanagement.azure.upbound.io/v1beta1
            kind: Management
            spec:
              forProvider:
                location: West Europe
                publisherEmail: company@terraform.io
                publisherName: My Company
                resourceGroupNameSelector:
                  matchControllerRef: true
                skuName: Developer_1
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.location"
              toFieldPath: "spec.forProvider.location"
              transforms:
                - type: map
                  map:
                    UK: "UK South"
                    USEast: "East US"
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.apiManagement.publisherEmail"
              toFieldPath: "spec.forProvider.publisherEmail"
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.apiManagement.publisherName"
              toFieldPath: "spec.forProvider.publisherName"
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.apiManagement.skuName"
              toFieldPath: "spec.forProvider.skuName"
            - type: PatchSet
              patchSetName: common-labels
        - name: subnet-apim
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: Subnet
            spec:
              forProvider:
                addressPrefixes:
                  - 10.0.1.0/24
                virtualNetworkNameSelector:
                  matchControllerRef: true
                resourceGroupNameSelector:
                  matchControllerRef: true
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.networking.subnetPrefix"
              toFieldPath: "spec.forProvider.addressPrefixes"
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.resourceNames.subnet"
              toFieldPath: "metadata.annotations[crossplane.io/external-name]"
              transforms:
                - type: string
                  string:
                    type: Format
                    fmt: "subnet-apim-%s"
            - type: PatchSet
              patchSetName: common-labels
        - name: vnet-dmz
          base:
            apiVersion: network.azure.upbound.io/v1beta1
            kind: VirtualNetwork
            spec:
              forProvider:
                addressSpace:
                  - 10.0.0.0/16
                location: "Central US"
                resourceGroupNameSelector:
                  matchControllerRef: true
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.location"
              toFieldPath: "spec.forProvider.location"
              transforms:
                - type: map
                  map:
                    UK: "UK South"
                    USEast: "East US"
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.networking.vnetAddressSpace"
              toFieldPath: "spec.forProvider.addressSpace"
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.resourceNames.vnet"
              toFieldPath: "metadata.annotations[crossplane.io/external-name]"
              transforms:
                - type: string
                  string:
                    type: Format
                    fmt: "vnet-%s"
            - type: PatchSet
              patchSetName: common-labels
        - name: resource-group-dmz
          base:
            apiVersion: azure.upbound.io/v1beta1
            kind: ResourceGroup
            spec:
              forProvider:
                location: Central US
          patches:
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.location"
              toFieldPath: "spec.forProvider.location"
              transforms:
                - type: map
                  map:
                    UK: "UK South"
                    USEast: "East US"
            - type: FromCompositeFieldPath
              fromFieldPath: "spec.name"
              toFieldPath: "metadata.annotations[crossplane.io/external-name]"
              transforms:
                - type: string
                  string:
                    type: Format
                    fmt: "rg-%s"
            - type: PatchSet
              patchSetName: common-labels
  compositeTypeRef:
    apiVersion: azure.platform.my-org.co/v1alpha1
    kind: XIngress